language: python
sudo: required
dist: xenial

python:
  - 3.6

git:
  depth: 9999

before_install:
  - sudo apt-get update
  - sudo apt-get -y install libnfft3-dev

install:
  - pip install Cython
  - pip install .

script:
   - exit 0
